=== sergmain/webmill/riverock-portlet/src/main/xsd/riverock-portlet-member.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 4 U (http://www.xmlspy.com) by Serg (Home) -->
<!--
/*
 * org.riverock.portlet - Portlet Library
 * 
 * Copyright (C) 2004, Riverock Software, All Rights Reserved.
 * 
 * Riverock - The Open-source Java Development Community
 * http://www.riverock.org
 * 
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *
 */
-->
<xs:schema elementFormDefault="qualified" attributeFormDefault="unqualified" xmlns:portlet="http://java.sun.com/xml/ns/portlet/portlet-app_1_0.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:annotation>
		<xs:documentation>Copyright 2002, riverock.org, http://www.riverock.org</xs:documentation>
	</xs:annotation>
	<xs:annotation>
		<xs:documentation>WebMill XML/XSLT web portlet engine</xs:documentation>
	</xs:annotation>
	<xs:element name="MemberArea">
		<xs:annotation>
			<xs:documentation xml:lang="ru">Root element</xs:documentation>
			<xs:documentation xml:lang="en">Root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Module" type="ModuleType" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Module</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="ModuleType">
		<xs:sequence>
			<xs:element name="RelateClass" type="RelateClassType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="SelfLookup" type="SelfLookupType" minOccurs="0"/>
			<xs:element name="Content" type="ContentType" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="authApplication" type="xs:string" use="required"/>
		<xs:attribute name="authModule" type="xs:string" use="required"/>
		<xs:attribute name="isDelete" type="xs:boolean" use="required"/>
		<xs:attribute name="type">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="lookup"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="lookupPK" type="xs:string"/>
		<xs:attribute name="maxRecord" type="xs:int"/>
	</xs:complexType>
	<xs:complexType name="ContentType">
		<xs:sequence>
			<xs:element name="security-role-ref" type="security-role-refType" maxOccurs="unbounded"/>
			<xs:element name="Title" type="MultiLangStringType"/>
			<xs:element name="QueryArea" type="QueryAreaType"/>
			<xs:element name="ActionButtonName" type="MultiLangStringType" minOccurs="0"/>
			<xs:element name="TargetAreaName" type="MultiLangStringType" minOccurs="0"/>
			<xs:element name="TargetModule" type="TargetModuleType" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="action" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="index"/>
					<xs:enumeration value="insert"/>
					<xs:enumeration value="change"/>
					<xs:enumeration value="delete"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="authRole" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:complexType name="security-role-refType">
		<xs:annotation>
			<xs:documentation>
			The security-role-ref element contains the declaration of a 
			security role reference in the code of the web application. The 
			declaration consists of an optional description, the security 
			role name used in the code, and an optional link to a security 
			role. If the security role is not specified, the Deployer must 
			choose an appropriate security role.
			The value of the role name element must be the String used 
			as the parameter to the 
			EJBContext.isCallerInRole(String roleName) method
			or the HttpServletRequest.isUserInRole(String role) method.
			Used in: portlet
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="description" type="descriptionType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="role-name" type="role-nameType"/>
			<xs:element name="role-link" type="role-linkType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:complexType name="descriptionType">
		<xs:simpleContent>
			<xs:extension base="xs:string"/>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="role-linkType">
		<xs:simpleContent>
			<xs:extension base="xs:string"/>
		</xs:simpleContent>
	</xs:complexType>
	<xs:simpleType name="role-nameType">
		<xs:annotation>
			<xs:documentation>
			The role-nameType designates the name of a security role.

			The name must conform to the lexical rules for an NMTOKEN.
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:NMTOKEN"/>
	</xs:simpleType>
	<xs:complexType name="RelateClassType">
		<xs:attribute name="isFullReinitCache" type="xs:boolean" use="required"/>
		<xs:attribute name="className" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="SelfLookupType">
		<xs:sequence>
			<xs:element name="CurrentField" type="SelfLookupFieldType"/>
			<xs:element name="TopField" type="SelfLookupFieldType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="QueryAreaType">
		<xs:sequence>
			<xs:element name="Restrict" type="RestrictType" minOccurs="0"/>
			<xs:element name="PrimaryKey" type="xs:string"/>
			<xs:element name="PrimaryKeyType">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="number"/>
						<xs:enumeration value="string"/>
						<xs:enumeration value="date"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="PrimaryKeyMask" type="xs:string" minOccurs="0"/>
			<xs:element name="MainRefTable" type="xs:string" minOccurs="0"/>
			<xs:element name="Fields" maxOccurs="unbounded">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="FieldsType"/>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="Table" type="TableType" maxOccurs="unbounded"/>
			<xs:element name="Where" type="xs:string" minOccurs="0"/>
			<xs:element name="WhereCompelx" type="SqlWhereType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Order" type="SortOrderType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="SqlCache" type="SqlCacheType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="FieldsType">
		<xs:sequence>
			<xs:element name="NameColumn" type="MultiLangStringType" minOccurs="0"/>
			<xs:element name="QueryArea" type="QueryAreaType" minOccurs="0"/>
			<xs:element name="ClassQuery" type="ClassQueryType" minOccurs="0"/>
			<xs:element name="Validator" type="FieldValidatorType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="isPk" type="xs:boolean"/>
		<xs:attribute name="refTable" type="xs:string"/>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="dbType" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="DATE"/>
					<xs:enumeration value="NUMBER"/>
					<xs:enumeration value="VARCHAR"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="isShow" type="xs:boolean" use="required"/>
		<xs:attribute name="isSelect" type="xs:boolean"/>
		<xs:attribute name="isCustom" type="xs:boolean" use="prohibited"/>
		<xs:attribute name="jspType" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="text"/>
					<xs:enumeration value="bigtext"/>
					<xs:enumeration value="bigtext_lob"/>
					<xs:enumeration value="date_text"/>
					<xs:enumeration value="float_text"/>
					<xs:enumeration value="double_text"/>
					<xs:enumeration value="lookup"/>
					<xs:enumeration value="text_area"/>
					<xs:enumeration value="yesno_switch"/>
					<xs:enumeration value="checkbox_switch"/>
					<xs:enumeration value="int_text"/>
					<xs:enumeration value="lookupClass"/>
					<xs:enumeration value="yes_1_no_n"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="mask" type="xs:string"/>
		<xs:attribute name="length" type="xs:int" default="5"/>
		<xs:attribute name="isEdit" type="xs:boolean" default="true"/>
		<xs:attribute name="isNotNull" type="xs:boolean" default="false"/>
		<xs:attribute name="defValue" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="ClassQueryType">
		<xs:sequence>
			<xs:element name="Parameters" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="ClassQueryParameterType"/>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="nameClass" type="xs:string" use="required"/>
		<xs:attribute name="nameOptionName" type="xs:string" use="required"/>
		<xs:attribute name="xmlRoot" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="SelfLookupFieldType">
		<xs:attribute name="refTable" type="xs:string" use="required"/>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="dbType" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="DATE"/>
					<xs:enumeration value="VARCHAR"/>
					<xs:enumeration value="NUMBER"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="MultiLangStringType">
		<xs:sequence>
			<xs:element name="StringData" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="isUseProperties" type="xs:boolean" use="required"/>
		<xs:attribute name="storage" type="xs:string"/>
		<xs:attribute name="isInit" type="xs:boolean"/>
	</xs:complexType>
	<xs:complexType name="RestrictType">
		<xs:attribute name="type" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="firm"/>
					<xs:enumeration value="site"/>
					<xs:enumeration value="user"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="SortOrderType">
		<xs:attribute name="field" type="xs:string" use="required"/>
		<xs:attribute name="direction">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="ASC"/>
					<xs:enumeration value="DESC"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="TableType">
		<xs:attribute name="table" type="xs:string" use="required"/>
		<xs:attribute name="ref" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="TargetModuleLookupType">
		<xs:attribute name="type" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="index"/>
					<xs:enumeration value="insert"/>
					<xs:enumeration value="change"/>
					<xs:enumeration value="delete"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="TargetModuleType">
		<xs:sequence>
			<xs:element name="TargetModuleName" type="MultiLangStringType"/>
			<xs:element name="TargetModuleLookup" type="TargetModuleLookupType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="action" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="index"/>
					<xs:enumeration value="insert"/>
					<xs:enumeration value="change"/>
					<xs:enumeration value="delete"/>
					<xs:enumeration value="lookup"/>
					<xs:enumeration value="self"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="module" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="ClassQueryParameterType">
		<xs:attribute name="method" type="xs:string" use="required"/>
		<xs:attribute name="field" type="xs:string" use="required"/>
		<xs:attribute name="type" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="java.lang.Long"/>
					<xs:enumeration value="java.lang.String"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="FieldValidatorType">
		<xs:attribute name="type">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="xml"/>
					<xs:enumeration value="xslt"/>
					<xs:enumeration value="bind_dynamic"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:element name="SqlCache" type="SqlCacheType"/>
	<xs:complexType name="SqlCacheType">
		<xs:sequence>
			<xs:element name="Field" type="SqlCacheFieldType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="CheckParam" type="SqlCheckParameterType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="From" type="SqlFromType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Where" type="SqlWhereType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Sql" type="xs:string" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="isInit" type="xs:boolean"/>
	</xs:complexType>
	<xs:complexType name="SqlCacheFieldType">
		<xs:sequence>
			<xs:element name="Alias" type="xs:string" minOccurs="0"/>
			<xs:element name="Name" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SqlCheckParameterType">
		<xs:sequence>
			<xs:element name="Parameter" type="xs:string"/>
			<xs:element name="ParameterType">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="number"/>
						<xs:enumeration value="string"/>
						<xs:enumeration value="date"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="type">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="http_request"/>
					<xs:enumeration value="restrict_site"/>
					<xs:enumeration value="restrict_firm"/>
					<xs:enumeration value="restrict_user"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="SqlFromType">
		<xs:sequence>
			<xs:element name="Table" type="xs:string"/>
			<xs:element name="Alias" type="xs:string" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SqlWhereType">
		<xs:sequence>
			<xs:element name="Comment" type="xs:string" minOccurs="0"/>
			<xs:element name="Left" type="SqlWhereColumnType"/>
			<xs:element name="Right" type="SqlWhereColumnType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SqlWhereColumnType">
		<xs:sequence>
			<xs:element name="Alias" type="xs:string" minOccurs="0"/>
			<xs:element name="Column" type="xs:string" minOccurs="0"/>
			<xs:element name="TypeField" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="field"/>
						<xs:enumeration value="data"/>
						<xs:enumeration value="parameter"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Value" type="xs:string" minOccurs="0"/>
			<xs:element name="SubQuery" type="SqlCacheType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="RelateClassListType">
		<xs:sequence>
			<xs:element name="RelateClass" type="RelateClassType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== sergmain/webmill/riverock-portlet/src/main/webapp/WEB-INF/webmill/member/b2x.shop_config.xml
<?xml version="1.0" encoding="windows-1251"?>
<!--
  ~ org.riverock.portlet - Portlet Library
  ~
  ~ Copyright (C) 2006, Riverock Software, All Rights Reserved.
  ~
  ~ Riverock - The Open-source Java Development Community
  ~ http://www.riverock.org
  ~
  ~
  ~ This program is free software; you can redistribute it and/or
  ~ modify it under the terms of the GNU General Public
  ~ License as published by the Free Software Foundation; either
  ~ version 2 of the License, or (at your option) any later version.
  ~
  ~ This library is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
  ~ General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public
  ~ License along with this library; if not, write to the Free Software
  ~ Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
  -->
<MemberArea xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\sandbox\riverock\riverock-portlet\src-schema\xsd\riverock-portlet-member.xsd" xmlns:portlet="http://java.sun.com/xml/ns/portlet/portlet-app_1_0.xsd">
	<Module name="b2x.shop_config" authApplication="PRICE" authModule="B2C.SHOP" isDelete="0">
		<Content action="index">
			<security-role-ref>
				<role-name>webmill.shop</role-name>
			</security-role-ref>
			<Title isUseProperties="0" storage="mill.locale.HAM_QSO_LOG">
				<StringData>Персональные скидки для клиентов</StringData>
			</Title>
			<QueryArea>
				<Restrict type="firm"/>
				<PrimaryKey>ID_USER</PrimaryKey>
				<PrimaryKeyType>number</PrimaryKeyType>
				<MainRefTable>a</MainRefTable>
				<Fields refTable="a" name="ID_USER" dbType="NUMBER" jspType="int_text" isShow="false"/>
				<Fields refTable="a" name="ID_FIRM" dbType="NUMBER" length="1" jspType="int_text" isShow="false">
					<NameColumn isUseProperties="1" storage="mill.locale.AUTH_USER">
						<StringData>index.jsp.is_road</StringData>
					</NameColumn>
				</Fields>
				<Fields refTable="a" name="LAST_NAME" dbType="VARCHAR" length="50" jspType="text" isShow="true">
					<NameColumn isUseProperties="0" storage="mill.locale.HAM_QSO_LOG">
						<StringData>Фамилия</StringData>
					</NameColumn>
				</Fields>
				<Fields refTable="a" name="FIRST_NAME" dbType="VARCHAR" length="50" jspType="text" isShow="true">
					<NameColumn isUseProperties="0" storage="mill.locale.HAM_QSO_LOG">
						<StringData>Имя</StringData>
					</NameColumn>
				</Fields>
				<Fields refTable="a" name="MIDDLE_NAME" dbType="VARCHAR" length="50" jspType="text" isShow="true">
					<NameColumn isUseProperties="0" storage="mill.locale.HAM_QSO_LOG">
						<StringData>Отчество</StringData>
					</NameColumn>
				</Fields>
				<Fields refTable="a" name="DISCOUNT" dbType="NUMBER" length="50" jspType="float_text" isShow="true">
					<NameColumn isUseProperties="0" storage="mill.locale.HAM_QSO_LOG">
						<StringData>Размер скидки</StringData>
					</NameColumn>
				</Fields>
				<Table table="WM_LIST_USER" ref="a"/>
				<!--Order field="date_create" direction="desc"/-->
			</QueryArea>
			<TargetAreaName isUseProperties="1" storage="mill.locale.HAM_QSO_LOG">
				<StringData>index.jsp.action</StringData>
			</TargetAreaName>
			<TargetModule action="index">
				<TargetModuleName isUseProperties="1" storage="mill.locale.main">
					<StringData>page.main.3</StringData>
				</TargetModuleName>
			</TargetModule>
			<TargetModule action="change">
				<TargetModuleName isUseProperties="0" storage="mill.locale.main">
					<StringData>Изменить скидку</StringData>
				</TargetModuleName>
			</TargetModule>
		</Content>
		<Content action="change">
			<security-role-ref>
				<role-name>webmill.shop</role-name>
			</security-role-ref>
			<Title isUseProperties="0" storage="mill.locale.HAM_QSO_LOG">
				<StringData>Изменение размера скидки для клиента</StringData>
			</Title>
			<QueryArea>
				<Restrict type="firm"/>
				<PrimaryKey>ID_USER</PrimaryKey>
				<PrimaryKeyType>number</PrimaryKeyType>
				<MainRefTable>a</MainRefTable>
				<Fields refTable="a" name="ID_USER" dbType="NUMBER" jspType="int_text" isShow="0"/>
				<Fields refTable="a" name="ID_FIRM" dbType="NUMBER" length="1" jspType="int_text" isShow="false">
					<NameColumn isUseProperties="1" storage="mill.locale.AUTH_USER">
						<StringData>index.jsp.is_road</StringData>
					</NameColumn>
				</Fields>
				<Fields refTable="a" name="LAST_NAME" dbType="VARCHAR" length="50" jspType="text" isShow="true" isEdit="false">
					<NameColumn isUseProperties="0" storage="mill.locale.HAM_QSO_LOG">
						<StringData>Фамилия</StringData>
					</NameColumn>
				</Fields>
				<Fields refTable="a" name="FIRST_NAME" dbType="VARCHAR" length="50" jspType="text" isShow="true" isEdit="false">
					<NameColumn isUseProperties="0" storage="mill.locale.HAM_QSO_LOG">
						<StringData>Имя</StringData>
					</NameColumn>
				</Fields>
				<Fields refTable="a" name="MIDDLE_NAME" dbType="VARCHAR" length="50" jspType="text" isShow="true" isEdit="false">
					<NameColumn isUseProperties="0" storage="mill.locale.HAM_QSO_LOG">
						<StringData>Отчество</StringData>
					</NameColumn>
				</Fields>
				<Fields refTable="a" name="DISCOUNT" dbType="NUMBER" length="50" jspType="float_text" isShow="true">
					<NameColumn isUseProperties="0" storage="mill.locale.HAM_QSO_LOG">
						<StringData>Размер скидки</StringData>
					</NameColumn>
				</Fields>
				<Table table="WM_LIST_USER" ref="a"/>
				<!--Order field="date_create" direction="desc"/-->
			</QueryArea>
			<TargetAreaName isUseProperties="1" storage="mill.locale.HAM_QSO_LOG">
				<StringData>index.jsp.action</StringData>
			</TargetAreaName>
			<TargetModule action="index">
				<TargetModuleName isUseProperties="1" storage="mill.locale.main">
					<StringData>page.main.3</StringData>
				</TargetModuleName>
			</TargetModule>
			<TargetModule action="change">
				<TargetModuleName isUseProperties="0" storage="mill.locale.main">
					<StringData>Изменение размера скидки</StringData>
				</TargetModuleName>
			</TargetModule>
		</Content>
	</Module>
</MemberArea>

=== sergmain/webmill/trunk/riverock-portlet/src/main/webapp/WEB-INF/webmill/member/stat.xml
<?xml version="1.0" encoding="windows-1251"?>
<!--
  ~ org.riverock.portlet - Portlet Library
  ~
  ~ Copyright (C) 2006, Riverock Software, All Rights Reserved.
  ~
  ~ Riverock - The Open-source Java Development Community
  ~ http://www.riverock.org
  ~
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~      http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->
<MemberArea xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\sandbox\riverock\riverock-portlet\src-schema\xsd\riverock-portlet-member.xsd" xmlns:portlet="http://java.sun.com/xml/ns/portlet/portlet-app_1_0.xsd">
	<Module name="mill.stat.useragent" authApplication="MILL.STAT" authModule="MILL.STAT.USER_AGENT" isDelete="true">
		<Content action="index">
			<security-role-ref>
				<role-name>webmill.admin</role-name>
			</security-role-ref>
			<Title isUseProperties="false">
				<StringData>Список используемых юзер агентов</StringData>
			</Title>
			<QueryArea>
				<PrimaryKey>ID_SITE_USER_AGENT</PrimaryKey>
				<PrimaryKeyType>number</PrimaryKeyType>
				<MainRefTable>a</MainRefTable>
				<Fields refTable="a" name="ID_SITE_USER_AGENT" dbType="NUMBER" jspType="int_text" isShow="true">
					<NameColumn isUseProperties="0" storage="mill.locale.HAM_QSO_LOG">
						<StringData>##</StringData>
					</NameColumn>
				</Fields>
				<Fields refTable="a" name="USER_AGENT" dbType="VARCHAR" length="150" jspType="text" isShow="true">
					<NameColumn isUseProperties="0" storage="mill.locale.HAM_QSO_LOG">
						<StringData>UserAgent</StringData>
					</NameColumn>
				</Fields>
				<Table table="WM_PORTAL_ACCESS_USERAGENT" ref="a"/>
				<Order field="ID_SITE_USER_AGENT" direction="ASC"/>
			</QueryArea>
			<TargetAreaName isUseProperties="false">
				<StringData>Type of action</StringData>
			</TargetAreaName>
			<TargetModule action="index">
				<TargetModuleName isUseProperties="0">
					<StringData>Index page</StringData>
				</TargetModuleName>
			</TargetModule>
		</Content>
	</Module>
</MemberArea>
