=== sergmain/webmill/riverock-webmill-updater/src/main/xsd/v580/riverock-template.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:element="http://webmill.riverock.org/xsd/riverock-template-page-elements.xsd" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:portal="http://webmill.riverock.org/xsd/riverock-template-elements.xsd" elementFormDefault="qualified" attributeFormDefault="unqualified" jaxb:version="2.0">
	<xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="xml.xsd"/>
	<xs:import namespace="http://webmill.riverock.org/xsd/riverock-template-page-elements.xsd" schemaLocation="riverock-template-page-elements.xsd"/>
	<xs:element name="SiteTemplate" type="SiteTemplate"/>
	<xs:complexType name="SiteTemplate">
		<xs:choice>
			<xs:element name="SiteTemplateItem" type="SiteTemplateItem" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>@deprecated use only XHTML markup</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:choice>
		<xs:attribute name="role" type="xs:string" use="optional"/>
		<xs:attribute name="language" type="xs:string" use="optional"/>
		<xs:attribute name="type" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:complexType name="SiteTemplateItem">
		<xs:sequence>
			<xs:element name="Parameter" type="Parameter" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="type" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="portlet"/>
					<xs:enumeration value="custom"/>
					<xs:enumeration value="file"/>
					<xs:enumeration value="dynamic"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="value" type="xs:string"/>
		<xs:attribute name="code" type="xs:string"/>
		<xs:attribute name="xmlRoot" type="xs:string"/>
		<xs:attribute name="role" type="xs:string"/>
		<xs:attribute name="template" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="Parameter">
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="value" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:element name="Template">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="element:dynamic"/>
				<xs:element ref="element:portlet"/>
				<xs:element ref="element:xslt"/>
				<xs:element ref="element:include"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== sergmain/webmill/riverock-webmill/src/test/resources/xml/resources/template/template_v2_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 rel. 3 U (http://www.altova.com) by Serg (Ru-Board) -->
<!DOCTYPE SiteTemplate SYSTEM "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<SiteTemplate role="test.role" xmlns:portal="http://webmill.riverock.org/xsd/riverock-template-portal-items" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\sandbox\riverock\trunk\riverock-webmill\src\main\xsd\riverock-template.xsd">
	<SiteTemplateItem type="custom" value="HeaderStart"/>
	<SiteTemplateItem type="custom" value="HeaderText"/>
	<SiteTemplateItem type="custom" value="HeaderEnd"/>
	<SiteTemplateItem type="portlet" value="mill.menu" code="TOP_MENU" xmlRoot="TopMenu" role="webmill.authentic"/>
	<SiteTemplateItem type="portlet" value="mill.login_xml" xmlRoot="LoginOnIndexPage"/>
	<SiteTemplateItem type="custom" value="MainStart"/>
	<SiteTemplateItem type="portlet" value="mill.menu"/>
	<SiteTemplateItem type="portlet" value="mill.menu_member"/>
	<SiteTemplateItem type="custom" value="Separator"/>
	<SiteTemplateItem type="portlet" value="mill.news_block"/>
	<SiteTemplateItem type="portlet" value="mill.menu" code="DEFAULT_ru_RU">
		<Parameter name="level" value="1"/>
		<Parameter name="type_level" value="equal"/>
	</SiteTemplateItem>
	<SiteTemplateItem type="portlet" value="mill.menu" code="DEFAULT_ru_RU">
		<Parameter name="level" value="1"/>
		<Parameter name="type_level" value="great"/>
	</SiteTemplateItem>
	<SiteTemplateItem type="custom" value="Footer"/>
</SiteTemplate>
