=== sergmain/webmill/riverock-module/src-schema/xsd/riverock-module-action.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" attributeFormDefault="unqualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="action-config" type="ActionConfigType"/>
	<xs:complexType name="ActionConfigType">
		<xs:sequence>
			<xs:element name="default-action" type="xs:string"/>
			<xs:element name="role" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="default-forward" type="ForwardType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="action" type="ActionType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ActionType">
		<xs:sequence>
			<xs:element name="role" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="forward" type="ForwardType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string"/>
		<xs:attribute name="path" type="xs:string" use="required"/>
		<xs:attribute name="default-forward" type="xs:string"/>
		<xs:attribute name="type" type="xs:string"/>
		<xs:attribute name="is-redirect" type="xs:boolean" default="false"/>
	</xs:complexType>
	<xs:complexType name="DefaultActionType">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ForwardType">
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="path" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="SecurityRoleType"/>
</xs:schema>

=== sergmain/webmill/riverock-portlet-register/src/main/webapp/WEB-INF/action/register-action.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
  ~ org.riverock.portlet - Portlet Library
  ~
  ~ Copyright (C) 2006, Riverock Software, All Rights Reserved.
  ~
  ~ Riverock - The Open-source Java Development Community
  ~ http://www.riverock.org
  ~
  ~
  ~ This program is free software; you can redistribute it and/or
  ~ modify it under the terms of the GNU General Public
  ~ License as published by the Free Software Foundation; either
  ~ version 2 of the License, or (at your option) any later version.
  ~
  ~ This library is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
  ~ General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public
  ~ License along with this library; if not, write to the Free Software
  ~ Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
  -->
<action-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\sandbox\riverock\riverock-module\src-schema\xsd\riverock-module-action.xsd">
	<default-action>home</default-action>
	<role>webmill.guest</role>
	<role>webmill.root</role>
	<default-forward name="error" path="/riverock/register/jsp/action-message.jsp"/>
	<default-forward name="system-error" path="/riverock/register/jsp/action-message.jsp"/>

    <action name="Help action" path="help" default-forward="/riverock/register/jsp/help.jsp" type="org.riverock.portlet.register.action.RegisterHelpAction"/>

	<action name="Home action" path="home" default-forward="/riverock/register/jsp/home.jsp" type="org.riverock.portlet.register.action.RegisterHomeAction"/>

	<action name="Send password action" path="send-password" type="org.riverock.portlet.register.action.SendPasswordAction">
		<forward name="ok" path="/riverock/register/jsp/send-password-ok.jsp"/>
<!--
		<forward name="error" path="/riverock/register/jsp/send-password-error.jsp"/>
-->
        <forward name="error" path="/riverock/register/jsp/home.jsp"/>
	</action>

	<action name="Create account action" path="create-account" type="org.riverock.portlet.register.action.CreateAccountAction">
		<forward name="ok" path="/riverock/register/jsp/create-account-ok.jsp"/>
<!--
		<forward name="error" path="/riverock/register/jsp/create-account-error.jsp"/>
-->
		<forward name="error" path="/riverock/register/jsp/home.jsp"/>
	</action>
</action-config>

=== sergmain/webmill/trunk/riverock-forum/web/WEB-INF/action/forum-action-manage-list.xml
<?xml version="1.0" encoding="UTF-8"?>
<action-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\sandbox\riverock\riverock-module\src-schema\xsd\riverock-module-action.xsd">
	<default-action>manage-forum-list</default-action>
	<role>webmill.forum-admin</role>
	<role>webmill.root</role>
	<default-forward name="access-denied" path="/riverock/forum/jsp/access-denied.jsp"/>
	<default-forward name="not-logged" path="/riverock/forum/jsp/not-logged.jsp"/>
	<default-forward name="error" path="/riverock/forum/jsp/action-message.jsp"/>
    <action name="Manage forum list" path="manage-forum-list" type="org.riverock.forum.action.ManageForumListAction">
        <forward name="ok" path="/riverock/forum/jsp/manage-forum-list.jsp"/>
    </action>
</action-config>
